version: 2.1

jobs:
  test:
    docker:
      - image: thecodingmachine/php:8.1-v4-cli

    steps:
      - run: cd /usr/src/app && git clone https://github.com/jonbaldie/eleven.git && cd eleven && composer install --prefer-dist --no-interaction
      - run: cd /usr/src/app/eleven && ./vendor/bin/psalm

workflows:
  test:
    jobs:
      - test
